{{- with $.Values.wellKnownDelegation -}}
{{- if .enabled -}}
{{- if .ingress.httpRoute -}}

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
{{- include "element-io.ess-library.ingress.annotations" (dict "root" $ "context" (dict "ingress" .ingress)) | nindent 2 }}
  labels:
    {{- include "element-io.well-known-delegation-ingress.labels" (dict "root" $ "context" $.Values.haproxy) | nindent 4 }}
  name: {{ $.Release.Name }}-well-known
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
  - name: {{ $.Values.httpRoute.gateway.name }}
    namespace: {{ $.Values.httpRoute.gateway.namespace }}
  hostnames:
  - "{{ tpl $.Values.serverName $ }}"
  rules:
{{- if and .baseDomainRedirect.enabled (or $.Values.elementWeb.enabled .baseDomainRedirect.url) }}
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: "{{ $.Release.Name }}-well-known"
      port: 8010
{{- else }}
  - matches:
    - path:
        type: PathPrefix
        value: /.well-known/matrix
    backendRefs:
    - name: "{{ $.Release.Name }}-well-known"
      port: 8010
{{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
