{{- with .Values.matrixAuthenticationService -}}
{{- if .enabled -}}
{{- if .ingress.httpRoute -}}

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
{{- include "element-io.ess-library.ingress.annotations" (dict "root" $ "context" (dict "ingress" .ingress)) | nindent 2 }}
  labels:
    {{- include "element-io.matrix-authentication-service.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-matrix-authentication-service
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
  - name: {{ $.Values.httpRoute.gateway.name }}
    namespace: {{ $.Values.httpRoute.gateway.namespace }}
  hostnames:
  - {{ (tpl .ingress.host $) | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: "{{ $.Release.Name }}-matrix-authentication-service"
      port: 8080
{{- end -}}
{{- end }}
{{- end }}
