{{- with .Values.matrixRTC -}}
{{- if .enabled -}}
{{- if .ingress.httpRoute -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
{{- $extraAnnotations := dict }}
{{- if .sfu.enabled }}
{{- if eq "ingress-nginx" (include "element-io.ess-library.ingress-controller-type" (dict "root" $ "context" .ingress.controllerType)) }}
{{- $_ := set $extraAnnotations "nginx.ingress.kubernetes.io/proxy-send-timeout" "120" }}
{{- $_ := set $extraAnnotations "nginx.ingress.kubernetes.io/proxy-read-timeout" "120" }}
{{- $_ := set $extraAnnotations "nginx.ingress.kubernetes.io/proxy-buffering" "off" }}
{{- end }}
{{- end }}
{{- include "element-io.ess-library.ingress.annotations" (dict "root" $ "context" (dict "ingress" .ingress "extraAnnotations" $extraAnnotations)) | nindent 2 }}
  labels:
    {{- include "element-io.matrix-rtc-ingress.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-matrix-rtc
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
  - name: {{ $.Values.httpRoute.gateway.name }}
    namespace: {{ $.Values.httpRoute.gateway.namespace }}
  hostnames:
  - {{ (tpl .ingress.host $) | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /sfu/get
    backendRefs:
    - name: "{{ $.Release.Name }}-matrix-rtc-authorisation-service"
      port: 8080
{{- if .sfu.enabled }}
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: "{{ $.Release.Name }}-matrix-rtc-sfu"
      port: 7880
{{- end -}}
{{- end }}
{{- end }}
{{- end }}
